### ISSUE TITLE
首屏没有出现滚动条时无法load内容

### ISSUE THREAD

**Issue by design-study** [thundernet8/React-Limited-Infinite-Scroll#1]
首屏没有出现滚动条时无法load内容

**Comment by thundernet8** [comment]
@ctpstudy 插件有两个重要的参数`pageStart`和`autoLoad`，那么有两种情况：

1. 首屏也就是第一页以及其他页面都由插件去加载，此时pageStart应该设为0，autoLoad应该设为true
2. 首屏由自己代码加载，获取一些必要的如total信息，有其他页面时用插件的加载更多，此时pageStart应该设为1，autoLoad设为false

**Comment by design-study** [comment]
非常感谢
