### ISSUE TITLE
使用您的这个组件发现一个问题

### ISSUE THREAD

**Issue by zhaoy0221** [thundernet8/React-Limited-Infinite-Scroll#3]
我在加载几页内容后，点击button切换数据源从第一页再次加载，这个时候下拉加载不再执行，望修复！！
PS：看到您有中文文档，就直接回复您了，英文不太好。。

**Comment by thundernet8** [comment]
@a-little-boy 能否提供下你的示例代码

**Comment by zhaoy0221** [comment]
![image](https://user-images.githubusercontent.com/27721311/32709137-3a42ef00-c869-11e7-83b3-834cfb34595c.png)

**Comment by zhaoy0221** [comment]
![image](https://user-images.githubusercontent.com/27721311/32709183-70ac30c4-c869-11e7-88b0-90ab5c313d2a.png)
这边点击这些按钮触发renderMore函数   只能加载新的列表一次   下拉无效

**Comment by thundernet8** [comment]
你的`hasMore`参数值`load_more`是如何定义的，目前组件didMount之后，如果`hasMore`为`false`就不会监听滚动事件了

**Comment by thundernet8** [comment]
Please reopen this if any problem

**Comment by kongdemin** [comment]
> 你的`hasMore`参数值`load_more`是如何定义的，目前组件didMount之后，如果`hasMore`为`false`就不会监听滚动事件了

那意思是切换tab之后需要把组件销毁掉 再重新渲染一个新的吗

**Comment by thundernet8** [comment]
> > 你的`hasMore`参数值`load_more`是如何定义的，目前组件didMount之后，如果`hasMore`为`false`就不会监听滚动事件了
> 
> 
> 
> 那意思是切换tab之后需要把组件销毁掉 再重新渲染一个新的吗

是这样的

**Comment by kongdemin** [comment]
是否可以修复下这种问题，类似这种场景还是挺多的。我尝试给组件加一个动态的key值，但还是不起作用。
